/*
 * Proxy Auto-Config file generated by uu
 */
function FindProxyForURL(url, host) {
  var PHTTP = "PROXY 127.0.0.1:4444";
  var PHTTPS= "PROXY 127.0.0.1:4445";
  var DEFAULT = "DIRECT";

  if(shExpMatch(url,"http:\/\/*.i2p\/*")) return PHTTP;
  if(shExpMatch(url,"https:\/\/*.i2p\/*")) return PHTTPS;
  if(shExpMatch(url,"http:\/\/*.onion\/*")) return PHTTP;
  if(shExpMatch(url,"https:\/\/*.onion\/*")) return PHTTPS;
  return DEFAULT;
}
